version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: taskgo_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: taskgo
      POSTGRES_USER: taskgo_user
      POSTGRES_PASSWORD: taskgo_dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskgo_user -d taskgo"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: taskgo_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@taskgo.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
